info:
  name: add-timeframe-30m
  type: http
  seq: 2

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/add-timeframe
  body:
    type: json
    data: |-
      {
        "id": "30m"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
