info:
  name: add-series-1h-ema50
  type: http
  seq: 7

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/add-series
  body:
    type: json
    data: |-
      {
        "timeframe_id": "1h",
        "id": "ema50",
        "kind": "EMA",
        "level": 1,
        "primary": false,
        "overlay": true,
        "params": {
          "label": "EMA 50",
          "layer": "foreground",
          "color": "#2962FF",
          "priceTagColor": "#2962FF",
          "lineWidth": 1,
          "period": 50
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
