info:
  name: set-risk
  type: http
  seq: 18

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/set-risk
  body:
    type: json
    data: |-
      {
        "config": {
          "stop": {
            "type": "percent",
            "value": 0.006
          },
          "targets": []
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
