info:
  name: set-strategy
  type: http
  seq: 10

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/set-strategy
  body:
    type: json
    data: |-
      {
        "kind": "Strategy1",
        "params": {
          "timeframe": "5m",
          "label_fast": "EMA 20",
          "label_slow": "EMA 50",
          "quantity": 1
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
